---
openapi: 3.0.1
info:
  title: issues2markdown
  description: Converts a list of issues and renders the result to markdown following
    the Github Flavoured Markdown task lists format.
  contact:
    name: Raül Pérez
    url: https://issues2markdown.com
    email: repejota@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: 0.0.1
paths:
  /teapot:
    get:
      description: Teapot
      responses:
        418: {
          "description": "I'm a teapot"
        }
